<?php
/*
 * Turiknox_AddressAutocomplete

 * @category   Turiknox
 * @package    Turiknox_AddressAutocomplete
 * @copyright  Copyright (c) 2017 Turiknox
 * @license    https://github.com/Turiknox/magento-address-autocomplete/blob/master/LICENSE.md
 * @version    1.0.0
 */
?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->escapeHtml($this->getApiKey()); ?>&libraries=places"></script>